# Generated by Django 3.1.7 on 2021-06-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='autoClickPower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maincycle',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('power', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=10)),
                ('boost_type', models.IntegerField(default=1)),
                ('mainCycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='user_profile.maincycle')),
            ],
        ),
    ]
